bookkeeping/config/routes.rb
Rails.application.routes.draw do
  root  'welcome#index'
  get   'users/new'
  get   'users/login'

  resources :users
end

bookkeeping/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookkeeping/app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, 
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

bookkeeping/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

bookkeeping/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
  
  def new
  end
  
  def create
    @user = User.new(user_params)
 
    @user.save
    redirect_to @user
  end
  
  def login
    
  end
  
  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

bookkeeping/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

bookkeeping/app/helpers/application_helper.rb
module ApplicationHelper
end

bookkeeping/app/helpers/users_helper.rb
module UsersHelper
end

bookkeeping/app/helpers/welcome_helper.rb
module WelcomeHelper
end

bookkeeping/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookkeeping</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

bookkeeping/app/views/users/login.html.erb
<h1>Einloggen</h1>
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit 'Einloggen'%>
  </p>
<% end %>

bookkeeping/app/views/users/new.html.erb
<h1>Create new User</h1>
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  
  <p>
    <%= f.label :password_wiederholen %><br>
    <%= f.password_field :password_confirmation %>
  </p>
 
  <p>
    <%= f.submit 'Benuter speichern'%>
  </p>
<% end %>

bookkeeping/app/views/users/show.html.erb
<p>
  <strong>Benutzer:</strong>
  <%= @user.email %>
</p>

bookkeeping/app/views/welcome/index.html.erb
<h1>Willkommen auf kibuso.de</h1>
<p>Hier können Sie kostenlos Ihre Buchhaltung führen.</p>
<p>Erstellen Sie ein Benutzerkonto, loggen Sie sich ein und führen Sie Ihre
Journalbuchungen durch. Kibuso.de erstellt alle notwendigen Bücher und
Konten. Die Buchungen aus dem Journal werden auf die Konten übertragen.
Sie können jederzeit den Jahresabschluss mit einem Click erstellen.</p>
<p>Wir wünschen Ihnen viel Spass</p>
<p>Dieser Service ist komplett kostenlos.</p>
<%= link_to "Benutzerkonto erstellen", users_new_path %>
<%= link_to "Als Benuter einloggen", users_login_path %>